import os
from pathlib import Path

TOKEN = "7905009014:AAGQ0wgLibwO0dPLzyA041AbMOCAK9PlrFA"
ADMIN_CHAT_ID = -1002585261529
MAX_ORDERS_PER_USER = 3
MAX_FILE_SIZE_MB = 5

BASE_DIR = Path(__file__).parent
UPLOAD_FOLDER = BASE_DIR / "uploads"
DB_NAME = BASE_DIR / "study_tips_bot.db"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)

(
    SELECTING_ACTION, SELECTING_ORDER_TYPE, ENTERING_SUBJECT,
    ENTERING_DESCRIPTION, ENTERING_DEADLINE, ENTERING_BUDGET,
    UPLOADING_FILE, CONFIRMING_ORDER, HANDLING_DISPUTE,
    ADMIN_MENU, EXECUTOR_MENU
) = range(11)